# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -std=c++11
CC       = gcc.exe -std=c++11
WINDRES  = windres.exe
OBJ      = myfirst.o
LINKOBJ  = myfirst.o
LIBS     = -L"C:/Users/Suryansh/Dev-Cpp/MinGW64/lib" -L"C:/Users/Suryansh/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Suryansh/Dev-Cpp/MinGW64/include" -I"C:/Users/Suryansh/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Suryansh/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Suryansh/Dev-Cpp/MinGW64/include" -I"C:/Users/Suryansh/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Suryansh/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Suryansh/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = myfirst.exe
CXXFLAGS = $(CXXINCS) -g
CFLAGS   = $(INCS) -g
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

myfirst.o: myfirst.cpp
	$(CPP) -c myfirst.cpp -o myfirst.o $(CXXFLAGS)
